import {DOC_IDS,GRAPH_NODES,WORKFLOW_NODES} from '../../server/dataset.js';
const datasetId='doyles-operations-2026-10-01';
const blank=()=>({schemaVersion:1,datasetId,snapshotId:'cloud',savedAt:'',issues:{},reviews:{},training:{},settings:{companionRoot:''}});
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
export function validContent(kind,id,v){if(!v||typeof v.title!=='string'||!v.title.trim()||v.title.length>200)return false;if(kind==='doc')return DOC_IDS.includes(id)&&typeof v.body==='string'&&v.body.length>0&&v.body.length<=150000;if(kind==='graph')return !!GRAPH_NODES[id]&&v.labels&&Object.keys(v.labels).length===GRAPH_NODES[id].length&&GRAPH_NODES[id].every(n=>typeof v.labels[n]==='string'&&v.labels[n].trim()&&v.labels[n].length<=4000);return false;}
export function validState(v){return !!v&&v.schemaVersion===1&&v.datasetId===datasetId&&v.training&&typeof v.training==='object'&&Object.entries(v.training).length<=500&&Object.entries(v.training).every(([id,r])=>/^r[a-z0-9]+$/.test(id)&&r&&WORKFLOW_NODES[r.workflow]&&Object.keys(r.steps||{}).every(n=>WORKFLOW_NODES[r.workflow].includes(n)))&&v.issues&&v.reviews;}
export async function onRequest(context){const {request,env,data}=context,user=data.user;if(!user)return json({error:'Verified sign-in required.'},401);if(!env.DB)return json({error:'D1 database binding is not configured.'},503);const [resource,kind,id]=new URL(request.url).pathname.slice(5).split('/');
 try{
 if(request.method==='GET'&&resource==='me')return json(user);
 if(request.method==='GET'&&resource==='content'){const result=await env.DB.prepare('SELECT id,kind,value,version FROM content').all();const value={docs:{},graphs:{}};for(const r of result.results)value[r.kind==='doc'?'docs':'graphs'][r.id.split(':').slice(1).join(':')]={...JSON.parse(r.value),version:r.version};return json(value);}
 if(request.method==='GET'&&resource==='state'){const row=await env.DB.prepare('SELECT value,version FROM user_state WHERE user_id=?').bind(user.id).first();return json(row?{value:JSON.parse(row.value),version:row.version}:{value:blank(),version:0});}
 if(request.method==='GET'&&resource==='dashboard'){if(!['admin','editor'].includes(user.role))return json({error:'Team dashboard access is restricted.'},403);const results=await env.DB.prepare('SELECT email,value,updated_at FROM user_state ORDER BY updated_at DESC LIMIT 100').all();const records=[];for(const row of results.results){const v=JSON.parse(row.value);for(const r of Object.values(v.training||{})){const steps=Object.values(r.steps||{});records.push({email:row.email,workflow:r.workflow,workflowTitle:r.workflowTitle||'',outcome:r.outcome||'Pending review',checked:steps.reduce((a,s)=>a+['discuss','observe','confirm'].filter(k=>s[k]===true).length,0),total:steps.length*3,updatedAt:row.updated_at});}}return json({records});}
 if(request.method!=='PUT'||!['content','state'].includes(resource))return json({error:'Unknown endpoint.'},404);
 if(resource==='content'&&!['admin','editor'].includes(user.role))return json({error:'Only authorized editors can publish wiki changes.'},403);
 const text=await request.text();if(text.length>750000)return json({error:'Record exceeds the size limit.'},413);let body;try{body=JSON.parse(text);}catch{return json({error:'Invalid JSON.'},400);}if(!Number.isSafeInteger(body.version)||body.version<0)return json({error:'A valid record version is required.'},400);
 if(resource==='content'&&!validContent(kind,id,body.value))return json({error:'Invalid wiki content or diagram labels.'},400);if(resource==='state'&&!validState(body.value))return json({error:'Invalid training workspace.'},400);
 const value=JSON.stringify(body.value),version=body.version+1,at=new Date().toISOString(),nonce=crypto.randomUUID();let update,audit;
 if(resource==='state'){
 const current=await env.DB.prepare('SELECT value FROM user_state WHERE user_id=?').bind(user.id).first();const old=current?JSON.parse(current.value):blank();if(user.role==='employee'){for(const [key,previous] of Object.entries(old.training||{})){if(previous.outcome==='Completed against recorded SOP'&&JSON.stringify(body.value.training[key])!==JSON.stringify(previous))return json({error:'Completed records require an authorized trainer/editor to reopen or change.'},403);}for(const r of Object.values(body.value.training)){const prev=old.training?.[r.id];if(r.outcome==='Completed against recorded SOP'&&prev?.outcome!==r.outcome)return json({error:'Completion approval requires an authorized trainer/editor.'},403);if(r.trainer_assessment&&r.trainer_assessment!==prev?.trainer_assessment)return json({error:'Trainer assessment requires an authorized trainer/editor.'},403);}}
 update=body.version===0?env.DB.prepare('INSERT INTO user_state(user_id,email,value,version,updated_at,write_nonce) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO NOTHING').bind(user.id,user.email,value,version,at,nonce):env.DB.prepare('UPDATE user_state SET value=?,version=?,updated_at=?,write_nonce=? WHERE user_id=? AND version=?').bind(value,version,at,nonce,user.id,body.version);
 audit=env.DB.prepare("INSERT INTO audit(actor,action,record_id,version,at,value) SELECT ?,'state-save',?,?,?,? FROM user_state WHERE user_id=? AND write_nonce=?").bind(user.email,'user:'+user.id,version,at,value,user.id,nonce);
 }else{const key=kind+':'+id;update=body.version===0?env.DB.prepare('INSERT INTO content(id,kind,value,version,updated_by,updated_at,write_nonce) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(key,kind,value,version,user.email,at,nonce):env.DB.prepare('UPDATE content SET value=?,version=?,updated_by=?,updated_at=?,write_nonce=? WHERE id=? AND version=?').bind(value,version,user.email,at,nonce,key,body.version);audit=env.DB.prepare("INSERT INTO audit(actor,action,record_id,version,at,value) SELECT ?,'content-save',?,?,?,? FROM content WHERE id=? AND write_nonce=?").bind(user.email,key,version,at,value,key,nonce);}
 const result=await env.DB.batch([update,audit]);if(!result[0].meta.changes)return json({error:'Another save changed this record. Reload cloud records before saving again; export your local edits first.'},409);return json({version,updatedAt:at});
 }catch(err){console.error('Workspace request failed',err.message);return json({error:'The database request failed. Your change is not confirmed saved.'},500);}
}
